#!/bin/sh
# https://kisslinux.org/wiki/package-manager#006

case $1 in
    pre-build)
        IFS=. read -r _start _ < /proc/uptime
        printf '%d' "$_start" > "${TMPDIR:-/tmp}/$2_start"
    ;;
    post-package)
        read -r _start < "${TMPDIR:-/tmp}/$2_start"
        IFS=. read -r _end _ < /proc/uptime
        rm "${TMPDIR:-/tmp}/$2_start"

        _s=$((_end - _start))
        _h=$((_s / 60 / 60 % 24))
        _m=$((_s / 60 % 60 ))

        [ "$_h" = 0 ] || _u="${_u}${_h}h "
        [ "$_m" = 0 ] || _u="${_u}${_m}m "

        printf '\033[1;33m-> \033[1;34m%s \033[m%s\n' "$2" \
               "Build finished in ~${_u:-${_s}s}" >&2
    ;;
esac
